variables:
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA #unix id
  JAR: "jar"
  NGINX: "nginx"

stages:
  - deploy
deploy:
  stage: deploy
  tags:
    - spring
  only:
    - /^live_[0-9]+(?:.[0-9]+)+$/ # regular expression live_0.0.1, live_0.0.2, live_0.0.3, etc.
  script:
    - echo "Building Jar"
    - mv ./src/main/resources/application.prod.properties ./src/main/resources/application.properties
    - mvn clean install -DskipTests #build file jar
    - echo "Build Jar Image" #start build image jar
    - docker build -t $TAG_COMMIT$JAR . #build image jar
    - echo "Build Nginx Image" #start build image nginx
    - docker build -t $TAG_COMMIT$NGINX ./nginx #build image nginx
    - chmod 600 $GITLAB_CI_SSH_KEY
    - docker container rm -f spring-boot-app || true
    - docker run -d -p 8088:8088 --name spring-boot-app --network="host" $TAG_COMMIT$JAR
    - docker container rm -f nginx-app || true
    - docker run -d -p 80:80 --network="host" --name nginx-app $TAG_COMMIT$NGINX
    - echo "Build Complete"
  environment:
    name: production
    url: http://$SERVER_HOST
